language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
